<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductCategory;
use Illuminate\Database\Seeder;

class ShopSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            [
                'name' => 'Template Hotspot MikroTik',
                'slug' => 'template-hotspot',
                'icon' => 'fa-wifi',
                'sort_order' => 0,
                'description' => 'Koleksi 30 Template Login Page MikroTik Desain Modern, Responsive Mobile & Desktop, dilengkapi Live Preview Simulator.',
            ],
            [
                'name' => 'Router & Switch MikroTik',
                'slug' => 'router-mikrotik',
                'icon' => 'fa-server',
                'sort_order' => 1,
                'description' => 'Routerboard dan Switch MikroTik handal untuk core gateway dan manajemen bandwidth ISP.',
            ],
            [
                'name' => 'OLT & ONT FTTH',
                'slug' => 'olt-ont-ftth',
                'icon' => 'fa-sitemap',
                'sort_order' => 2,
                'description' => 'Perangkat OLT GPON/EPON (ZTE, Huawei, HSGQ, V-SOL) dan modem ONT/ONU klien.',
            ],
            [
                'name' => 'SFP & Aksesoris Fiber',
                'slug' => 'sfp-aksesoris-fiber',
                'icon' => 'fa-plug',
                'sort_order' => 3,
                'description' => 'Modul SFP PON C++/C+++, Patchcord SC-UPC/APC, Attenuator, dan ODP.',
            ],
            [
                'name' => 'Server & Mini PC Cloud',
                'slug' => 'server-mini-pc',
                'icon' => 'fa-laptop',
                'sort_order' => 4,
                'description' => 'Mini PC hemat daya & Server siap pakai terinstal NODERA Docker Standalone.',
            ],
        ];

        foreach ($categories as $catData) {
            ProductCategory::updateOrCreate(
                ['slug' => $catData['slug']],
                $catData
            );
        }

        $cHotspot = ProductCategory::where('slug', 'template-hotspot')->first();
        $cRouter = ProductCategory::where('slug', 'router-mikrotik')->first();
        $cOlt = ProductCategory::where('slug', 'olt-ont-ftth')->first();
        $cSfp = ProductCategory::where('slug', 'sfp-aksesoris-fiber')->first();
        $cServer = ProductCategory::where('slug', 'server-mini-pc')->first();

        $products = [
            [
                'category_id' => $cHotspot?->id,
                'name' => 'Bundle 30 Template Hotspot MikroTik Suite Full Edition',
                'slug' => 'bundle-30-template-hotspot-mikrotik',
                'sku' => 'HS-BUNDLE-30',
                'price' => 150000,
                'original_price' => 350000,
                'stock' => 999,
                'badge' => 'FULL PACK',
                'image' => '/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-ocean-abyss/preview-login.png',
                'gallery' => [
                    '/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-ocean-abyss/preview-login.png',
                    '/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-bento-grid/preview-login.png',
                    '/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-glass-dock/preview-login.png',
                    '/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-cyber-matrix/preview-login.png',
                ],
                'short_description' => 'Paket Komplit 30 Desain Template Login Page MikroTik dengan 11 file companion lengkap, responsive HP & PC, dan live preview simulator.',
                'description' => "Paket Terlengkap 30 Desain Template Login Page MikroTik Hotspot.\n\nKeunggulan Utama:\n• 30 Pilihan Desain Bespoke (Glass Dock, Bento Grid, Cyber Matrix, Anime Mecha, Tokyo Night, Fintech Wallet, dll).\n• 11 File Standar MikroTik per Tema (login, status, logout, redirect, alogin, flogin, error, radvert, rlogin, errors.txt, md5.js).\n• 100% Responsive Mobile & Desktop.\n• 5 Modal Interaktif: Daftar Paket, Cara Login, Rekening Pembayaran/QRIS, CS WhatsApp, dan FAQ.\n• Kompatibel MikroTik RouterOS v6 & v7.",
                'specifications' => "Kategori: Digital Template Hotspot\nJumlah Tema: 30 Desain Komplit (330 File)\nFile per Tema: 11 File Resmi MikroTik\nKompatibilitas: RouterOS v6 & v7 (Semua Tipe RouterBOARD & x86)\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-ocean-abyss/login.html",
                'is_featured' => true,
                'sort_order' => 0,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Glass Dock Edition",
                'slug' => "template-hotspot-glass-dock",
                'sku' => "HS-GLASS-DOCK",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "BESTSELLER",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-glass-dock/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-glass-dock/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-glass-dock/preview-status.png",
                ],
                'short_description' => "Desain Frosted Glass Split Dashboard dengan floating navbar & 5 modal interaktif.",
                'description' => "Template Hotspot MikroTik - Glass Dock Edition menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-glass-dock/login.html",
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Bento Grid Edition",
                'slug' => "template-hotspot-bento-grid",
                'sku' => "HS-BENTO-GRID",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "MODERN",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-bento-grid/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-bento-grid/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-bento-grid/preview-status.png",
                ],
                'short_description' => "Desain Asymmetric Dark Bento Deck premium dengan visual bento interaktif.",
                'description' => "Template Hotspot MikroTik - Bento Grid Edition menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-bento-grid/login.html",
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Cyber Matrix Cockpit",
                'slug' => "template-hotspot-cyber-matrix",
                'sku' => "HS-CYBER-MATRIX",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "TACTICAL",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-cyber-matrix/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-cyber-matrix/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-cyber-matrix/preview-status.png",
                ],
                'short_description' => "Desain Terminal Matrix HUD Green Cockpit dengan animasi radar & telemetry.",
                'description' => "Template Hotspot MikroTik - Cyber Matrix Cockpit menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-cyber-matrix/login.html",
                'is_featured' => false,
                'sort_order' => 3,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Anime Mecha Cockpit",
                'slug' => "template-hotspot-anime-mecha",
                'sku' => "HS-ANIME-MECHA",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "ANIME",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-anime-mecha/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-anime-mecha/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-anime-mecha/preview-status.png",
                ],
                'short_description' => "Desain EVA Tactical Pilot Cockpit HUD dengan visual mecha futuristic.",
                'description' => "Template Hotspot MikroTik - Anime Mecha Cockpit menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-anime-mecha/login.html",
                'is_featured' => false,
                'sort_order' => 4,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Tokyo Night Cyberpunk",
                'slug' => "template-hotspot-tokyo-night",
                'sku' => "HS-TOKYO-NIGHT",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "NEON",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-tokyo-night/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-tokyo-night/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-tokyo-night/preview-status.png",
                ],
                'short_description' => "Desain Neon Synthwave Tokyo Night dengan aksen ungu-magenta berkilau.",
                'description' => "Template Hotspot MikroTik - Tokyo Night Cyberpunk menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-tokyo-night/login.html",
                'is_featured' => false,
                'sort_order' => 5,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Fintech Neo-Wallet",
                'slug' => "template-hotspot-fintech-wallet",
                'sku' => "HS-FINTECH-WALLET",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "FINTECH",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-fintech-wallet/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-fintech-wallet/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-fintech-wallet/preview-status.png",
                ],
                'short_description' => "Desain Modern Mobile Banking & E-Wallet dengan kartu saldo interaktif.",
                'description' => "Template Hotspot MikroTik - Fintech Neo-Wallet menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-fintech-wallet/login.html",
                'is_featured' => false,
                'sort_order' => 6,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Luxury Black & Gold VIP",
                'slug' => "template-hotspot-black-gold",
                'sku' => "HS-BLACK-GOLD",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "VIP LUXURY",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-black-gold/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-black-gold/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-black-gold/preview-status.png",
                ],
                'short_description' => "Desain Mewah Hitam Emas Elegan untuk Hotel, Cafe Eksekutif & Lounge VIP.",
                'description' => "Template Hotspot MikroTik - Luxury Black & Gold VIP menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-black-gold/login.html",
                'is_featured' => false,
                'sort_order' => 7,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Pixel Art Arcade 8-Bit",
                'slug' => "template-hotspot-pixel-arcade",
                'sku' => "HS-PIXEL-ARCADE",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "RETRO",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-pixel-arcade/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-pixel-arcade/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-pixel-arcade/preview-status.png",
                ],
                'short_description' => "Desain Nostalgia Retro Gaming Arcade 8-Bit dengan font piksel autentik.",
                'description' => "Template Hotspot MikroTik - Pixel Art Arcade 8-Bit menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-pixel-arcade/login.html",
                'is_featured' => false,
                'sort_order' => 8,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Ocean Abyss Subsea",
                'slug' => "template-hotspot-ocean-abyss",
                'sku' => "HS-OCEAN-ABYSS",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "SUBSEA",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-ocean-abyss/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-ocean-abyss/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-ocean-abyss/preview-status.png",
                ],
                'short_description' => "Desain Samudra Dalam Bioluminescent Cyan dengan visual trench fiber laut.",
                'description' => "Template Hotspot MikroTik - Ocean Abyss Subsea menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-ocean-abyss/login.html",
                'is_featured' => true,
                'sort_order' => 9,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Swiss Minimalist Grid",
                'slug' => "template-hotspot-swiss-minimal",
                'sku' => "HS-SWISS-MINIMAL",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "MINIMAL",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-swiss-minimal/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-swiss-minimal/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-swiss-minimal/preview-status.png",
                ],
                'short_description' => "Desain Tipografi Swiss Modern berstruktur grid bersih dengan rasio kontras prima.",
                'description' => "Template Hotspot MikroTik - Swiss Minimalist Grid menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-swiss-minimal/login.html",
                'is_featured' => false,
                'sort_order' => 10,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Neo-Brutalist Pop",
                'slug' => "template-hotspot-neo-brutalist",
                'sku' => "HS-NEO-BRUTALIST",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "POP ART",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-neo-brutalist/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-neo-brutalist/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-neo-brutalist/preview-status.png",
                ],
                'short_description' => "Desain Pop-Art Neo-Brutalist dengan border tegas tebal dan bayangan solid.",
                'description' => "Template Hotspot MikroTik - Neo-Brutalist Pop menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-neo-brutalist/login.html",
                'is_featured' => false,
                'sort_order' => 11,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Aurora Glow Glass",
                'slug' => "template-hotspot-aurora-glow",
                'sku' => "HS-AURORA-GLOW",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "AURORA",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-aurora-glow/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-aurora-glow/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-aurora-glow/preview-status.png",
                ],
                'short_description' => "Desain Gradien Cahaya Aurora Luminous Glass Pill yang memikat mata.",
                'description' => "Template Hotspot MikroTik - Aurora Glow Glass menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-aurora-glow/login.html",
                'is_featured' => false,
                'sort_order' => 12,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Steampunk Industrial",
                'slug' => "template-hotspot-steampunk-industrial",
                'sku' => "HS-STEAMPUNK-IND",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "VINTAGE",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-steampunk-industrial/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-steampunk-industrial/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-steampunk-industrial/preview-status.png",
                ],
                'short_description' => "Desain Vintage Victorian Brass Gear & Dial HUD bertema mekanik industri.",
                'description' => "Template Hotspot MikroTik - Steampunk Industrial menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-steampunk-industrial/login.html",
                'is_featured' => false,
                'sort_order' => 13,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Retro Vaporwave 80s",
                'slug' => "template-hotspot-retro-vaporwave",
                'sku' => "HS-RETRO-VAPOR",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "SYNTHWAVE",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-retro-vaporwave/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-retro-vaporwave/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-retro-vaporwave/preview-status.png",
                ],
                'short_description' => "Desain Synthwave Wireframe Sunset & Pohon Palem bernuansa era 80-an.",
                'description' => "Template Hotspot MikroTik - Retro Vaporwave 80s menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-retro-vaporwave/login.html",
                'is_featured' => false,
                'sort_order' => 14,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Soft Neumorphic 3D",
                'slug' => "template-hotspot-soft-neumorphic",
                'sku' => "HS-SOFT-NEUMORPH",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "CLEAN UI",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-soft-neumorphic/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-soft-neumorphic/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-soft-neumorphic/preview-status.png",
                ],
                'short_description' => "Desain 3D Extruded Soft UI bersih dan minimalis tanpa bayangan tajam.",
                'description' => "Template Hotspot MikroTik - Soft Neumorphic 3D menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-soft-neumorphic/login.html",
                'is_featured' => false,
                'sort_order' => 15,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Paper Origami Craft",
                'slug' => "template-hotspot-paper-origami",
                'sku' => "HS-PAPER-ORIGAMI",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "CRAFT",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-paper-origami/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-paper-origami/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-paper-origami/preview-status.png",
                ],
                'short_description' => "Desain Kertas Lipat Origami Taktil dengan tumpukan layer bayangan alami.",
                'description' => "Template Hotspot MikroTik - Paper Origami Craft menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-paper-origami/login.html",
                'is_featured' => false,
                'sort_order' => 16,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Gaming RGB Esports HUD",
                'slug' => "template-hotspot-gaming-hud",
                'sku' => "HS-GAMING-HUD",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "GAMING",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-gaming-hud/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-gaming-hud/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-gaming-hud/preview-status.png",
                ],
                'short_description' => "Desain Esports Neon Cyberpunk Stats Gauge Cockpit untuk kafe gaming & warnet.",
                'description' => "Template Hotspot MikroTik - Gaming RGB Esports HUD menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-gaming-hud/login.html",
                'is_featured' => false,
                'sort_order' => 17,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Enterprise SaaS Pro",
                'slug' => "template-hotspot-enterprise-pro",
                'sku' => "HS-ENTERPRISE-PRO",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "ENTERPRISE",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-enterprise-pro/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-enterprise-pro/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-enterprise-pro/preview-status.png",
                ],
                'short_description' => "Desain Executive Corporate Portal Glass Slate untuk kantor & hotel bintang 5.",
                'description' => "Template Hotspot MikroTik - Enterprise SaaS Pro menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-enterprise-pro/login.html",
                'is_featured' => false,
                'sort_order' => 18,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Artisan Cafe & Coffee Bar",
                'slug' => "template-hotspot-artisan-cafe",
                'sku' => "HS-ARTISAN-CAFE",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "CAFE",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-artisan-cafe/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-artisan-cafe/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-artisan-cafe/preview-status.png",
                ],
                'short_description' => "Desain Warm Espresso Kraft Paper & Coffee Bar hangat untuk kedai kopi & resto.",
                'description' => "Template Hotspot MikroTik - Artisan Cafe & Coffee Bar menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-artisan-cafe/login.html",
                'is_featured' => false,
                'sort_order' => 19,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Cosmic Nebula Space",
                'slug' => "template-hotspot-cosmic-nebula",
                'sku' => "HS-COSMIC-NEBULA",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "SPACE",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-cosmic-nebula/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-cosmic-nebula/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-cosmic-nebula/preview-status.png",
                ],
                'short_description' => "Desain Galaksi Kosmik Deep Space Violet Stardust Orb berkilau megah.",
                'description' => "Template Hotspot MikroTik - Cosmic Nebula Space menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-cosmic-nebula/login.html",
                'is_featured' => false,
                'sort_order' => 20,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Isometric Space Station",
                'slug' => "template-hotspot-isometric-station",
                'sku' => "HS-ISOMETRIC-STN",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "3D TECH",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-isometric-station/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-isometric-station/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-isometric-station/preview-status.png",
                ],
                'short_description' => "Desain Orbital 3D Tech Deck Module bertema stasiun antariksa masa depan.",
                'description' => "Template Hotspot MikroTik - Isometric Space Station menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-isometric-station/login.html",
                'is_featured' => false,
                'sort_order' => 21,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Stealth Tactical Ops",
                'slug' => "template-hotspot-stealth-tactical",
                'sku' => "HS-STEALTH-TACT",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "STEALTH",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-stealth-tactical/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-stealth-tactical/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-stealth-tactical/preview-status.png",
                ],
                'short_description' => "Desain Military Spec Dark Carbon Radar HUD dengan tampilan radar taktis.",
                'description' => "Template Hotspot MikroTik - Stealth Tactical Ops menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-stealth-tactical/login.html",
                'is_featured' => false,
                'sort_order' => 22,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Space Orbital Flight Deck",
                'slug' => "template-hotspot-space-orbital",
                'sku' => "HS-SPACE-ORBITAL",
                'price' => 35000,
                'original_price' => 50000,
                'stock' => 999,
                'badge' => "AVIONICS",
                'image' => "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-space-orbital/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-space-orbital/preview-login.png",
                    "/hotspot-themes/01_SIGNATURE_STYLES/dgtlnet-space-orbital/preview-status.png",
                ],
                'short_description' => "Desain Telemetry Avionics Cyan HUD dengan indikator instrumen penerbangan orbital.",
                'description' => "Template Hotspot MikroTik - Space Orbital Flight Deck menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/01_SIGNATURE_STYLES/dgtlnet-space-orbital/login.html",
                'is_featured' => false,
                'sort_order' => 23,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Classic Blue Edition T2",
                'slug' => "template-hotspot-biru-t2",
                'sku' => "HS-BIRU-T2",
                'price' => 25000,
                'original_price' => 35000,
                'stock' => 999,
                'badge' => "POPULER",
                'image' => "/hotspot-themes/02_CLASSIC_BESTSELLER/dgtlnet-biru-t2/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/02_CLASSIC_BESTSELLER/dgtlnet-biru-t2/preview-login.png",
                    "/hotspot-themes/02_CLASSIC_BESTSELLER/dgtlnet-biru-t2/preview-status.png",
                ],
                'short_description' => "Desain Biru Klasik Favorit Pengusaha WiFi dengan tampilan voucher jelas.",
                'description' => "Template Hotspot MikroTik - Classic Blue Edition T2 menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/02_CLASSIC_BESTSELLER/dgtlnet-biru-t2/login.html",
                'is_featured' => false,
                'sort_order' => 24,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Classic Blue Edition T4",
                'slug' => "template-hotspot-biru-t4",
                'sku' => "HS-BIRU-T4",
                'price' => 25000,
                'original_price' => 35000,
                'stock' => 999,
                'badge' => "POPULER",
                'image' => "/hotspot-themes/02_CLASSIC_BESTSELLER/dgtlnet-biru-t4/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/02_CLASSIC_BESTSELLER/dgtlnet-biru-t4/preview-login.png",
                    "/hotspot-themes/02_CLASSIC_BESTSELLER/dgtlnet-biru-t4/preview-status.png",
                ],
                'short_description' => "Desain Biru Klasik T4 Kontras Tinggi dengan kartu voucher yang mudah dibaca.",
                'description' => "Template Hotspot MikroTik - Classic Blue Edition T4 menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/02_CLASSIC_BESTSELLER/dgtlnet-biru-t4/login.html",
                'is_featured' => false,
                'sort_order' => 25,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Neon Cyan Edition",
                'slug' => "template-hotspot-tema-cyan",
                'sku' => "HS-TEMA-CYAN",
                'price' => 25000,
                'original_price' => 35000,
                'stock' => 999,
                'badge' => "WARNA",
                'image' => "/hotspot-themes/03_COLORWAY_EDITIONS/dgtlnet-tema-cyan/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/03_COLORWAY_EDITIONS/dgtlnet-tema-cyan/preview-login.png",
                    "/hotspot-themes/03_COLORWAY_EDITIONS/dgtlnet-tema-cyan/preview-status.png",
                ],
                'short_description' => "Colorway Neon Cyan cerah dengan kontras tinggi untuk visibilitas maksimal di luar ruangan.",
                'description' => "Template Hotspot MikroTik - Neon Cyan Edition menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/03_COLORWAY_EDITIONS/dgtlnet-tema-cyan/login.html",
                'is_featured' => false,
                'sort_order' => 26,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Emerald Forest Edition",
                'slug' => "template-hotspot-tema-emerald",
                'sku' => "HS-TEMA-EMERALD",
                'price' => 25000,
                'original_price' => 35000,
                'stock' => 999,
                'badge' => "WARNA",
                'image' => "/hotspot-themes/03_COLORWAY_EDITIONS/dgtlnet-tema-emerald/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/03_COLORWAY_EDITIONS/dgtlnet-tema-emerald/preview-login.png",
                    "/hotspot-themes/03_COLORWAY_EDITIONS/dgtlnet-tema-emerald/preview-status.png",
                ],
                'short_description' => "Colorway Hijau Zamrud Mint cerah dengan palet natural yang menyejukkan mata.",
                'description' => "Template Hotspot MikroTik - Emerald Forest Edition menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/03_COLORWAY_EDITIONS/dgtlnet-tema-emerald/login.html",
                'is_featured' => false,
                'sort_order' => 27,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Solar Amber Gold Edition",
                'slug' => "template-hotspot-tema-amber",
                'sku' => "HS-TEMA-AMBER",
                'price' => 25000,
                'original_price' => 35000,
                'stock' => 999,
                'badge' => "WARNA",
                'image' => "/hotspot-themes/03_COLORWAY_EDITIONS/dgtlnet-tema-amber/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/03_COLORWAY_EDITIONS/dgtlnet-tema-amber/preview-login.png",
                    "/hotspot-themes/03_COLORWAY_EDITIONS/dgtlnet-tema-amber/preview-status.png",
                ],
                'short_description' => "Colorway Solar Amber Gold hangat bernuansa senja keemasan dengan energi tinggi.",
                'description' => "Template Hotspot MikroTik - Solar Amber Gold Edition menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/03_COLORWAY_EDITIONS/dgtlnet-tema-amber/login.html",
                'is_featured' => false,
                'sort_order' => 28,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Crimson Ruby Edition",
                'slug' => "template-hotspot-tema-crimson",
                'sku' => "HS-TEMA-CRIMSON",
                'price' => 25000,
                'original_price' => 35000,
                'stock' => 999,
                'badge' => "WARNA",
                'image' => "/hotspot-themes/03_COLORWAY_EDITIONS/dgtlnet-tema-crimson/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/03_COLORWAY_EDITIONS/dgtlnet-tema-crimson/preview-login.png",
                    "/hotspot-themes/03_COLORWAY_EDITIONS/dgtlnet-tema-crimson/preview-status.png",
                ],
                'short_description' => "Colorway Merah Crimson Ruby agresif dengan aksen neon berani dan tegas.",
                'description' => "Template Hotspot MikroTik - Crimson Ruby Edition menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/03_COLORWAY_EDITIONS/dgtlnet-tema-crimson/login.html",
                'is_featured' => false,
                'sort_order' => 29,
            ],
            [
                'category_id' => $cHotspot?->id,
                'name' => "Template Hotspot MikroTik - Monochrome Minimal Edition",
                'slug' => "template-hotspot-tema-monochrome",
                'sku' => "HS-TEMA-MONO",
                'price' => 25000,
                'original_price' => 35000,
                'stock' => 999,
                'badge' => "WARNA",
                'image' => "/hotspot-themes/03_COLORWAY_EDITIONS/dgtlnet-tema-monochrome/preview-login.png",
                'gallery' => [
                    "/hotspot-themes/03_COLORWAY_EDITIONS/dgtlnet-tema-monochrome/preview-login.png",
                    "/hotspot-themes/03_COLORWAY_EDITIONS/dgtlnet-tema-monochrome/preview-status.png",
                ],
                'short_description' => "Colorway Hitam Putih Monokrom Zinc murni dengan kontras tinggi ultra bersih.",
                'description' => "Template Hotspot MikroTik - Monochrome Minimal Edition menghadirkan nuansa modern premium dengan responsivitas tinggi di smartphone dan desktop. Dilengkapi 11 file resmi RouterOS dan 5 modal popup interaktif.",
                'specifications' => "Tipe: Digital Template Single Theme\nFile: 11 File Lengkap RouterOS\nFitur: Responsive Mobile & PC, 5 Modal Interaktif, QRIS Ready\nPreview URL: /shop/preview-hotspot/03_COLORWAY_EDITIONS/dgtlnet-tema-monochrome/login.html",
                'is_featured' => false,
                'sort_order' => 30,
            ],
            [
                'category_id' => $cRouter?->id,
                'name' => 'MikroTik RouterBOARD RB750Gr3 (hEX)',
                'slug' => 'mikrotik-rb750gr3-hex',
                'sku' => 'RB750GR3',
                'price' => 850000,
                'original_price' => 950000,
                'stock' => 25,
                'badge' => 'TERLARIS',
                'image' => '/images/landing/mobile-dashboard.jpg',
                'short_description' => 'Router 5 port Gigabit Ethernet hemat daya, dual core 880MHz dengan dukungan hardware encryption & routing cepat.',
                'description' => 'MikroTik hEX (RB750Gr3) adalah router ethernet 5 port Gigabit untuk lokasi jaringan yang tidak membutuhkan wireless interface. Dilengkapi prosesor Dual Core 880MHz yang bertenaga, RAM 256MB, slot microSD untuk penyimpanan proxy/user manager, dan port USB full size.',
                'specifications' => "Arsitektur: MMIPS\nCPU: MT7621A 2 Core 4 Threads 880MHz\nRAM: 256 MB\nStorage: 16 MB Flash + Slot MicroSD\nPort: 5x 10/100/1000 Gigabit Ethernet\nOS: RouterOS v7 Level 4",
                'is_featured' => true,
                'sort_order' => 101,
            ],
            [
                'category_id' => $cRouter?->id,
                'name' => 'MikroTik Cloud Core Router CCR2004-16G-2S+',
                'slug' => 'mikrotik-ccr2004-16g-2splus',
                'sku' => 'CCR2004-16G-2S+',
                'price' => 7850000,
                'original_price' => 8500000,
                'stock' => 10,
                'badge' => 'PRO ISP',
                'image' => '/images/landing/traffic-monitor.png',
                'short_description' => 'Flagship core router 16 port Gigabit RJ45 dan 2 port 10G SFP+ dengan prosesor 4-Core 64-bit AL32400 1.7GHz.',
                'description' => 'CCR2004-16G-2S+ memberikan kinerja single-core paling kuat di kelasnya. Sangat ideal untuk core router ISP, BGP routing, PPPoE server ribuan klien, dan firewall shaping tingkat tinggi tanpa bottleneck.',
                'specifications' => "CPU: AL32400 4 Cores 1.7 GHz\nRAM: 4 GB DDR4\nStorage: 128 MB NAND\nPort: 16x 10/100/1000 Gigabit, 2x 10G SFP+\nDual Redundant Power Supply\nOS: RouterOS v7 Level 6",
                'is_featured' => true,
                'sort_order' => 102,
            ],
            [
                'category_id' => $cOlt?->id,
                'name' => 'OLT GPON V-SOL 8 Port (V1600G1-B)',
                'slug' => 'olt-gpon-vsol-8-port',
                'sku' => 'VSOL-V1600G1-B',
                'price' => 12500000,
                'original_price' => 13800000,
                'stock' => 8,
                'badge' => 'HOT',
                'image' => '/images/landing/olt-monitoring.png',
                'short_description' => 'OLT GPON Standalone 8 Port PON (1:128 split ratio hingga 1024 ONT), 4x GE Uplink + 2x 10GE SFP+ Uplink.',
                'description' => 'OLT GPON 8 Port dengan kompatibilitas penuh integrasi NODERA NMS. Mendukung auto-provisioning ONT, pemantauan status optik laser RX/TX real-time, dan manajemen VLAN PPPoE terpusat.',
                'specifications' => "Port PON: 8x GPON Port (SFP Class C++/C+++)\nUplink: 4x Gigabit RJ45, 2x 10GE SFP+\nSplit Ratio: 1:128 (Maksimal 1024 ONT)\nJarak Transmisi: 20 KM\nPower Supply: Dual AC+DC Redundant\nManajemen: Web, CLI, SNMP, NODERA NMS Integration",
                'is_featured' => true,
                'sort_order' => 103,
            ],
            [
                'category_id' => $cOlt?->id,
                'name' => 'Modem ONT GPON XPON Gigabit Dual Band AC1200',
                'slug' => 'modem-ont-xpon-ac1200-dual-band',
                'sku' => 'ONT-XPON-AC1200',
                'price' => 245000,
                'original_price' => 280000,
                'stock' => 150,
                'badge' => 'PROMO',
                'image' => '/images/landing/mobile-pppoe.jpg',
                'short_description' => 'ONT XPON (GPON/EPON) 4 Port LAN Gigabit, 1 Port PON SC/UPC, WiFi Dual Band 2.4GHz + 5GHz AC1200 4 Antena.',
                'description' => 'ONT klien berkecepatan tinggi mendukung mode Bridge & Router PPPoE, TR-069 GenieACS auto config, OMCI standard, dan jangkauan sinyal WiFi tembus dinding berkat antena gain 5dBi.',
                'specifications' => "Mode: GPON / EPON Auto Adaptive\nPort: 1x SC/UPC PON, 4x Gigabit LAN, 1x USB\nWiFi: AC1200 Dual Band (300Mbps di 2.4G + 867Mbps di 5G)\nAntena: 4x 5dBi High Gain External\nFitur: TR-069 GenieACS, PPPoE Client, Port Forwarding, Multi-SSID",
                'is_featured' => true,
                'sort_order' => 104,
            ],
            [
                'category_id' => $cSfp?->id,
                'name' => 'Modul SFP GPON OLT Class C+++ 20dBm (7.5dBm TX)',
                'slug' => 'sfp-gpon-olt-cplusplus',
                'sku' => 'SFP-GPON-C3P',
                'price' => 320000,
                'original_price' => 380000,
                'stock' => 60,
                'badge' => 'BEST QUALITY',
                'image' => '/images/landing/mobile-maps.jpg',
                'short_description' => 'Transceiver SFP GPON OLT kelas tertinggi C+++ daya pancar kuat +7.5dBm, sensitivitas -32dBm untuk redaman stabil.',
                'description' => 'SFP OLT C+++ original dirancang khusus untuk kabel jarak jauh FTTH, menjamin daya pancar laser tetap stabil dan mencegah packet loss akibat redaman split berlebih.',
                'specifications' => "Wavelength: TX 1490nm / RX 1310nm\nOptical Power TX: +5.5dBm s/d +8.5dBm\nSensitivity RX: -32 dBm\nKonektor: SC/UPC\nKompatibilitas: ZTE, Huawei, V-SOL, HSGQ, BDCOM",
                'is_featured' => false,
                'sort_order' => 105,
            ],
            [
                'category_id' => $cServer?->id,
                'name' => 'Mini PC Server NODERA Appliance Intel N100 16GB RAM SSD 512GB',
                'slug' => 'mini-pc-server-nodera-appliance-n100',
                'sku' => 'SRV-NODERA-N100',
                'price' => 3450000,
                'original_price' => 3900000,
                'stock' => 12,
                'badge' => 'SIAP PAKAI',
                'image' => '/images/landing/customers-billing.png',
                'short_description' => 'Server Mini PC hemat daya 15W siap pakai, terpasang Ubuntu Linux Server & NODERA Billing Docker Lifetime.',
                'description' => 'Solusi server on-premise siap colok untuk ISP & WISP. Menggunakan prosesor Intel Alder Lake N100 4-Core berkecepatan hingga 3.4GHz dengan konsumsi listrik sangat rendah (12-15 Watt). Mampu menangani hingga 10.000 pelanggan aktif dan puluhan router MikroTik tanpa lag.',
                'specifications' => "CPU: Intel 12th Gen Alder Lake N100 (4 Cores / 4 Threads up to 3.4GHz)\nRAM: 16 GB DDR5 4800MHz\nStorage: 512 GB NVMe PCIe M.2 SSD\nNetworking: Dual 2.5G Intel Ethernet Port (i226-V)\nDisplay: 2x HDMI 4K 60Hz\nPower: DC 12V 3A (Hemat listrik 15 Watt)\nSoftware Pre-installed: Ubuntu 24.04 LTS, Docker Engine, NODERA Billing Standalone Lifetime",
                'is_featured' => true,
                'sort_order' => 106,
            ],
        ];

        foreach ($products as $pData) {
            Product::updateOrCreate(
                ['slug' => $pData['slug']],
                $pData
            );
        }
    }
}
